x-variables:
  image-name: &image-name etf-matcher-data-encoder:latest

x-base-service: &base-service
  image: *image-name
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
  environment:
    - FORCE_COLOR=1
    - RUST_BACKTRACE=1

services:
  encode:
    <<: *base-service
    command: |
      sh -c '
      rm -rf /app/out &&
      mkdir -p /app/out &&
      ./docker_build_helpers/encode_data.sh &&
      cp -r /build_artifacts/out/. /app/out/
      '
