[package]
name = "encrypt_tool"
version = "0.1.0"
edition = "2018"

[dependencies]
aes = "0.7"
block-modes = "0.8"
flate2 = "1.0"
hmac = "0.11"
pbkdf2 = "0.9"
rand = "0.8"
sha2 = "0.9"
hex-literal = "0.3"
dotenv = "0.15"